/**
 * Round-trip tests for the Helm D1 schema (PDX-22).
 *
 * These run against an in-memory `better-sqlite3` database with the
 * generated migration applied. We don't spin up real D1; the SQL
 * generated by drizzle-kit for the `sqlite` dialect is byte-compatible
 * with D1, so this exercises the same shape.
 */

import { readFileSync } from "node:fs";
import { resolve } from "node:path";

import Database from "better-sqlite3";
import { and, eq } from "drizzle-orm";
import { drizzle } from "drizzle-orm/better-sqlite3";
import { afterEach, beforeEach, describe, expect, it } from "vitest";

import {
  auditLog,
  resources,
  sessions,
  shares,
  syncEvents,
  tasks,
  users,
  workspaces
} from "../src/db/schema.js";

type TestDb = ReturnType<typeof drizzle>;

const MIGRATION_PATH = resolve(__dirname, "../migrations/0000_init.sql");

function applyInitMigration(sqlite: Database.Database): void {
  const sql = readFileSync(MIGRATION_PATH, "utf8");
  // The generated migration uses `--> statement-breakpoint` separators.
  const statements = sql
    .split(/-->\s*statement-breakpoint/g)
    .map((s) => s.trim())
    .filter((s) => s.length > 0);
  // Foreign keys are off by default in SQLite; turn them on for tests.
  sqlite.pragma("foreign_keys = ON");
  for (const stmt of statements) {
    sqlite.exec(stmt);
  }
}

describe("Helm D1 schema", () => {
  let sqlite: Database.Database;
  let db: TestDb;

  beforeEach(() => {
    sqlite = new Database(":memory:");
    applyInitMigration(sqlite);
    db = drizzle(sqlite);
  });

  afterEach(() => {
    sqlite.close();
  });

  it("inserts a user and reads it back by email", async () => {
    await db.insert(users).values({ id: "u1", email: "alice@example.com" });

    const rows = await db
      .select()
      .from(users)
      .where(eq(users.email, "alice@example.com"))
      .all();

    expect(rows).toHaveLength(1);
    expect(rows[0]?.id).toBe("u1");
    expect(rows[0]?.email).toBe("alice@example.com");
    expect(rows[0]?.createdAt).toBeInstanceOf(Date);
  });

  it("enforces unique emails on users", async () => {
    await db.insert(users).values({ id: "u1", email: "dup@example.com" });
    await expect(
      db.insert(users).values({ id: "u2", email: "dup@example.com" })
    ).rejects.toThrow(/UNIQUE/i);
  });

  it("rolls a workspace -> resource -> share chain end to end", async () => {
    await db.insert(users).values([
      { id: "owner", email: "owner@example.com" },
      { id: "guest", email: "guest@example.com" }
    ]);
    await db.insert(workspaces).values({
      id: "w1",
      ownerUserId: "owner",
      name: "Helm dev"
    });
    await db.insert(resources).values({
      id: "r1",
      workspaceId: "w1",
      kind: "doc",
      payload: { title: "Hello" },
      version: 1
    });
    await db.insert(shares).values({
      id: "s1",
      resourceId: "r1",
      sharedWithUserId: "guest",
      permission: "read"
    });

    const sharedToGuest = await db
      .select()
      .from(shares)
      .where(eq(shares.sharedWithUserId, "guest"))
      .all();
    expect(sharedToGuest).toHaveLength(1);
    expect(sharedToGuest[0]?.resourceId).toBe("r1");
    expect(sharedToGuest[0]?.permission).toBe("read");

    const r = await db.select().from(resources).where(eq(resources.id, "r1")).all();
    expect(r[0]?.payload).toEqual({ title: "Hello" });
  });

  it("rejects sync_events that violate the per-user sequence uniqueness", async () => {
    await db.insert(users).values({ id: "u1", email: "u1@example.com" });
    await db.insert(workspaces).values({ id: "w1", ownerUserId: "u1", name: "w" });
    await db.insert(resources).values({
      id: "r1",
      workspaceId: "w1",
      kind: "doc",
      payload: {},
      version: 1
    });

    await db.insert(syncEvents).values({
      id: "e1",
      userId: "u1",
      resourceId: "r1",
      kind: "created",
      sequence: 1
    });
    await expect(
      db.insert(syncEvents).values({
        id: "e2",
        userId: "u1",
        resourceId: "r1",
        kind: "updated",
        sequence: 1
      })
    ).rejects.toThrow(/UNIQUE/i);
  });

  it("supports session -> task lifecycle with json result payload", async () => {
    await db.insert(users).values({ id: "u1", email: "u1@example.com" });
    await db.insert(sessions).values({
      id: "sess1",
      userId: "u1",
      agentId: "warp-default"
    });
    await db.insert(tasks).values({
      id: "task1",
      sessionId: "sess1",
      prompt: "say hi",
      status: "queued"
    });

    await db
      .update(tasks)
      .set({ status: "succeeded", result: { reply: "hi" } })
      .where(eq(tasks.id, "task1"));

    const all = await db
      .select()
      .from(tasks)
      .where(and(eq(tasks.sessionId, "sess1"), eq(tasks.status, "succeeded")))
      .all();
    expect(all).toHaveLength(1);
    expect(all[0]?.result).toEqual({ reply: "hi" });
  });

  it("audit_log accepts both attributed (PDX-23) and system (PDX-28) actions", async () => {
    await db.insert(users).values({ id: "u1", email: "u1@example.com" });

    // PDX-23 style: a user-attributed auth event
    await db.insert(auditLog).values({
      id: "a1",
      userId: "u1",
      action: "auth.signin",
      targetKind: "user",
      targetId: "u1",
      details: { provider: "passkey" }
    });

    // PDX-28 style: a system-fired guardrail trip with no user_id
    await db.insert(auditLog).values({
      id: "a2",
      userId: null,
      action: "guardrail.trip",
      targetKind: "skill",
      targetId: "shell-exec",
      details: { policy: "deny", reason: "unsafe path" }
    });

    const rows = await db.select().from(auditLog).all();
    expect(rows).toHaveLength(2);
    const guardrail = rows.find((r) => r.action === "guardrail.trip");
    expect(guardrail?.userId).toBeNull();
    expect(guardrail?.details).toEqual({ policy: "deny", reason: "unsafe path" });
  });
});
